# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'killer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for killer
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Fabric'
    pod 'Crashlytics'


  target 'killerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'killerUITests' do
    # Pods for testing
  end

end
